<div class="snippet" lang="vb" src="solidworks-api/data-storage/custom-properties/read-summary-information/Macro.vba"><pre class="prettyprint lang-vb">Dim swApp As SldWorks.SldWorks

Sub main()

    Set swApp = Application.SldWorks
    
    Dim swModel As SldWorks.ModelDoc2
    
    Set swModel = swApp.ActiveDoc
    
    If Not swModel Is Nothing Then
        Debug.Print "Author: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoAuthor)
        Debug.Print "Keywords: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoKeywords)
        Debug.Print "Comments: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoComment)
        Debug.Print "Title: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoTitle)
        Debug.Print "Subject: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoSubject)
        
        Debug.Print "Created: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoCreateDate2)
        Debug.Print "Last Saved: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoSaveDate2)
        Debug.Print "Last Saved By: " &amp; swModel.SummaryInfo(swSummInfoField_e.swSumInfoSavedBy)
        Debug.Print "Last Saved With: " &amp; GetLastSavedWith(swModel)
    Else
        MsgBox "Please open model"
    End If
    
End Sub

Function GetLastSavedWith(model As SldWorks.ModelDoc2) As String
    
    Dim vHistory As Variant
    vHistory = model.VersionHistory()
    
    Dim vers As String
    vers = vHistory(UBound(vHistory))
    
    vers = Mid(vers, InStr(vers, "[") + 1, 4)
    
    GetLastSavedWith = "SOLIDWORKS " &amp; vers
    
End Function</pre></div>