<div class="snippet" lang="cs" src="solidworks-api/getting-started/inter-process-communication/in-process-invoking/stand-alone/FaceIndexerCallback.cs"><pre class="prettyprint lang-cs">using CodeStack.FaceIndexer;
using SolidWorks.Interop.sldworks;
using System;
using System.Runtime.InteropServices;

namespace StandAlone
{
    [ComVisible(true)]
    public class FaceIndexerCallback : IFaceIndexerCallback
    {
        public void IndexFacesCompleted(IAssemblyDoc assm, int count)
        {
            Console.WriteLine($"Indexing completed in '{(assm as IModelDoc2).GetTitle()}' for {count} face(s) in stand-alone application");
        }
    }
}
</pre></div>